# Generated by Django 3.1.5 on 2021-02-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_auto_20210201_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainTest',
        ),
    ]
